export const CURRENCIES = [
  {
    code: "USD",
    name: "US Dollar",
    symbol: "$",
    flag: "🇺🇸",
    country: "United States",
    rateToBDT: 122.50,
    buyRate: 121.80,
    sellRate: 122.95,
    change24h: 0.25,
    category: "popular",
    popularTag: "Most Popular",
    region: "Americas",
  },
  {
    code: "SAR",
    name: "Saudi Riyal",
    symbol: "﷼",
    flag: "🇸🇦",
    country: "Saudi Arabia",
    rateToBDT: 32.65,
    buyRate: 32.20,
    sellRate: 32.85,
    change24h: 0.08,
    category: "middle-east",
    popularTag: "Umrah / Hajj",
    region: "Middle East",
  },
  {
    code: "AED",
    name: "UAE Dirham",
    symbol: "د.إ",
    flag: "🇦🇪",
    country: "United Arab Emirates",
    rateToBDT: 33.35,
    buyRate: 32.95,
    sellRate: 33.55,
    change24h: 0.15,
    category: "middle-east",
    popularTag: "Dubai Travel",
    region: "Middle East",
  },
  {
    code: "BDT",
    name: "Bangladeshi Taka",
    symbol: "৳",
    flag: "🇧🇩",
    country: "Bangladesh",
    rateToBDT: 1.00,
    buyRate: 1.00,
    sellRate: 1.00,
    change24h: 0.00,
    category: "local",
    popularTag: "Local Currency",
    region: "South Asia",
  },
  {
    code: "EUR",
    name: "Euro",
    symbol: "€",
    flag: "🇪🇺",
    country: "European Union",
    rateToBDT: 132.80,
    buyRate: 131.60,
    sellRate: 133.40,
    change24h: -0.18,
    category: "europe",
    popularTag: "Schengen Visa",
    region: "Europe",
  },
  {
    code: "GBP",
    name: "British Pound",
    symbol: "£",
    flag: "🇬🇧",
    country: "United Kingdom",
    rateToBDT: 156.40,
    buyRate: 155.10,
    sellRate: 157.20,
    change24h: 0.32,
    category: "europe",
    popularTag: "UK Study & Visit",
    region: "Europe",
  },
  {
    code: "MYR",
    name: "Malaysian Ringgit",
    symbol: "RM",
    flag: "🇲🇾",
    country: "Malaysia",
    rateToBDT: 28.15,
    buyRate: 27.85,
    sellRate: 28.35,
    change24h: 0.10,
    category: "asia",
    popularTag: "Medical & Tour",
    region: "Asia",
  },
  {
    code: "THB",
    name: "Thai Baht",
    symbol: "฿",
    flag: "🇹🇭",
    country: "Thailand",
    rateToBDT: 3.62,
    buyRate: 3.55,
    sellRate: 3.68,
    change24h: 0.05,
    category: "asia",
    popularTag: "Holiday & Visa",
    region: "Asia",
  },
  {
    code: "SGD",
    name: "Singapore Dollar",
    symbol: "S$",
    flag: "🇸🇬",
    country: "Singapore",
    rateToBDT: 92.40,
    buyRate: 91.60,
    sellRate: 93.10,
    change24h: 0.20,
    category: "asia",
    popularTag: "Transit & Tour",
    region: "Asia",
  },
  {
    code: "INR",
    name: "Indian Rupee",
    symbol: "₹",
    flag: "🇮🇳",
    country: "India",
    rateToBDT: 1.43,
    buyRate: 1.40,
    sellRate: 1.45,
    change24h: -0.05,
    category: "asia",
    popularTag: "Medical Travel",
    region: "South Asia",
  },
  {
    code: "CAD",
    name: "Canadian Dollar",
    symbol: "C$",
    flag: "🇨🇦",
    country: "Canada",
    rateToBDT: 87.20,
    buyRate: 86.20,
    sellRate: 87.90,
    change24h: 0.12,
    category: "americas",
    popularTag: "Student & Visit",
    region: "Americas",
  },
  {
    code: "AUD",
    name: "Australian Dollar",
    symbol: "A$",
    flag: "🇦🇺",
    country: "Australia",
    rateToBDT: 79.50,
    buyRate: 78.50,
    sellRate: 80.20,
    change24h: -0.10,
    category: "asia",
    popularTag: "Immigration & Tour",
    region: "Oceania",
  },
  {
    code: "QAR",
    name: "Qatari Riyal",
    symbol: "QR",
    flag: "🇶🇦",
    country: "Qatar",
    rateToBDT: 33.60,
    buyRate: 33.10,
    sellRate: 33.85,
    change24h: 0.04,
    category: "middle-east",
    popularTag: "Transit & Work",
    region: "Middle East",
  },
  {
    code: "KWD",
    name: "Kuwaiti Dinar",
    symbol: "KD",
    flag: "🇰🇼",
    country: "Kuwait",
    rateToBDT: 398.20,
    buyRate: 394.00,
    sellRate: 401.50,
    change24h: 0.18,
    category: "middle-east",
    popularTag: "Highest Value",
    region: "Middle East",
  },
  {
    code: "JPY",
    name: "Japanese Yen",
    symbol: "¥",
    flag: "🇯🇵",
    country: "Japan",
    rateToBDT: 0.81,
    buyRate: 0.79,
    sellRate: 0.83,
    change24h: -0.22,
    category: "asia",
    popularTag: "East Asia",
    region: "Asia",
  },
];

export function getCurrencyByCode(code) {
  return CURRENCIES.find((c) => c.code === code) || CURRENCIES[0];
}

export function calculateExchange(amount, fromCode, toCode) {
  const from = getCurrencyByCode(fromCode);
  const to = getCurrencyByCode(toCode);

  if (!amount || isNaN(amount) || amount <= 0) {
    return {
      convertedAmount: 0,
      exchangeRate: 1,
      inverseRate: 1,
    };
  }

  // Convert to BDT first as base
  const amountInBDT = amount * from.rateToBDT;
  // Convert from BDT to target currency
  const converted = amountInBDT / to.rateToBDT;
  const exchangeRate = from.rateToBDT / to.rateToBDT;
  const inverseRate = to.rateToBDT / from.rateToBDT;

  return {
    convertedAmount: converted,
    exchangeRate,
    inverseRate,
  };
}
