export const flights = [
  {
    id: 1,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "08:30 AM",
    arrival: "09:30 AM",
    duration: "1h 15m",
    stop: "Non Stop",
    price: 9999,
    baggage: "30 KG",
    refundable: true,
  },
  {
    id: 2,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "11:00 AM",
    arrival: "12:10 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 10500,
    baggage: "30 KG",
    refundable: false,
  },
  {
    id: 3,
    airline: "US Bangla Airlines",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmbTS0Ke1BYPm9zPFhzQ6fCAb3DjkDMqZ3uw&s",
    from: "DAC",
    to: "CXB",
    departure: "06:45 PM",
    arrival: "07:55 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 11200,
    baggage: "20 KG",
    refundable: true,
  },
  {
    id: 4,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "08:30 AM",
    arrival: "09:30 AM",
    duration: "1h 15m",
    stop: "Non Stop",
    price: 9999,
    baggage: "30 KG",
    refundable: true,
  },
  {
    id: 5,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "11:00 AM",
    arrival: "12:10 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 10500,
    baggage: "30 KG",
    refundable: false,
  },
  {
    id: 6,
    airline: "US Bangla Airlines",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmbTS0Ke1BYPm9zPFhzQ6fCAb3DjkDMqZ3uw&s",
    from: "DAC",
    to: "CXB",
    departure: "06:45 PM",
    arrival: "07:55 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 11200,
    baggage: "20 KG",
    refundable: true,
  },
  {
    id: 7,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "08:30 AM",
    arrival: "09:30 AM",
    duration: "1h 15m",
    stop: "Non Stop",
    price: 9999,
    baggage: "30 KG",
    refundable: true,
  },
  {
    id: 8,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "11:00 AM",
    arrival: "12:10 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 10500,
    baggage: "30 KG",
    refundable: false,
  },
  {
    id: 9,
    airline: "US Bangla Airlines",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmbTS0Ke1BYPm9zPFhzQ6fCAb3DjkDMqZ3uw&s",
    from: "DAC",
    to: "CXB",
    departure: "06:45 PM",
    arrival: "07:55 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 11200,
    baggage: "20 KG",
    refundable: true,
  },
  {
    id: 10,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "08:30 AM",
    arrival: "09:30 AM",
    duration: "1h 15m",
    stop: "Non Stop",
    price: 9999,
    baggage: "30 KG",
    refundable: true,
  },
  {
    id: 11,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "11:00 AM",
    arrival: "12:10 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 10500,
    baggage: "30 KG",
    refundable: false,
  },
  {
    id: 12,
    airline: "US Bangla Airlines",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmbTS0Ke1BYPm9zPFhzQ6fCAb3DjkDMqZ3uw&s",
    from: "DAC",
    to: "CXB",
    departure: "06:45 PM",
    arrival: "07:55 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 11200,
    baggage: "20 KG",
    refundable: true,
  },
  {
    id: 13,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "08:30 AM",
    arrival: "09:30 AM",
    duration: "1h 15m",
    stop: "Non Stop",
    price: 9999,
    baggage: "30 KG",
    refundable: true,
  },
  {
    id: 14,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "11:00 AM",
    arrival: "12:10 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 10500,
    baggage: "30 KG",
    refundable: false,
  },
  {
    id: 15,
    airline: "US Bangla Airlines",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmbTS0Ke1BYPm9zPFhzQ6fCAb3DjkDMqZ3uw&s",
    from: "DAC",
    to: "CXB",
    departure: "06:45 PM",
    arrival: "07:55 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 11200,
    baggage: "20 KG",
    refundable: true,
  },
  {
    id: 16,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "08:30 AM",
    arrival: "09:30 AM",
    duration: "1h 15m",
    stop: "Non Stop",
    price: 9999,
    baggage: "30 KG",
    refundable: true,
  },
  {
    id: 17,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "11:00 AM",
    arrival: "12:10 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 10500,
    baggage: "30 KG",
    refundable: false,
  },
  {
    id: 18,
    airline: "US Bangla Airlines",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmbTS0Ke1BYPm9zPFhzQ6fCAb3DjkDMqZ3uw&s",
    from: "DAC",
    to: "CXB",
    departure: "06:45 PM",
    arrival: "07:55 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 11200,
    baggage: "20 KG",
    refundable: true,
  },
  {
    id: 19,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "08:30 AM",
    arrival: "09:30 AM",
    duration: "1h 15m",
    stop: "Non Stop",
    price: 9999,
    baggage: "30 KG",
    refundable: true,
  },
  {
    id: 20,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "11:00 AM",
    arrival: "12:10 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 10500,
    baggage: "30 KG",
    refundable: false,
  },
  {
    id: 21,
    airline: "US Bangla Airlines",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmbTS0Ke1BYPm9zPFhzQ6fCAb3DjkDMqZ3uw&s",
    from: "DAC",
    to: "CXB",
    departure: "06:45 PM",
    arrival: "07:55 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 11200,
    baggage: "20 KG",
    refundable: true,
  },
  {
    id: 22,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "08:30 AM",
    arrival: "09:30 AM",
    duration: "1h 15m",
    stop: "Non Stop",
    price: 9999,
    baggage: "30 KG",
    refundable: true,
  },
  {
    id: 23,
    airline: "Biman Bangladesh Airlines",
    logo: "https://1000logos.net/wp-content/uploads/2023/05/Biman-Bangladesh-Airlines-Logo.png",
    from: "DAC",
    to: "CXB",
    departure: "11:00 AM",
    arrival: "12:10 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 10500,
    baggage: "30 KG",
    refundable: false,
  },
  {
    id: 24,
    airline: "US Bangla Airlines",
    logo: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRmbTS0Ke1BYPm9zPFhzQ6fCAb3DjkDMqZ3uw&s",
    from: "DAC",
    to: "CXB",
    departure: "06:45 PM",
    arrival: "07:55 PM",
    duration: "1h 10m",
    stop: "Non Stop",
    price: 11200,
    baggage: "20 KG",
    refundable: true,
  },
];
